### ISSUE TITLE
Sheep model gets disfigured when eating grass

### ISSUE THREAD

**Issue by CreepahJacket** [YoungSoulluoS/Fresh-Animations-CEM-fork#10]
# What I expected
The sheep should look fine when it eats the grass.
# What I got
The sheep becomes disfigured when it eats the grass.
# Screenshot
![2022-09-18_20 48 27](https://user-images.githubusercontent.com/66506817/190909864-72b9d2cc-db8b-4995-a068-424ba692e964.png)

**Comment by SoulxluoS** [comment]
Ok, need test

**Comment by SoulxluoS** [comment]
rollback baby heads and this animation normal work

**Comment by marklangerhacker** [comment]
Mr. YoungSoulluoS, did you forgot about that issue
I mean you forgot to mark it as fixed
