### ISSUE TITLE
The animals have whit eeyes and no animations

### ISSUE THREAD

**Issue by Omnimanoncrack** [YoungSoulluoS/Fresh-Animations-CEM-fork#11]
I am using this and the cem fork and it won't work. It looks the same as when you have custom entity models off in the optifine settings. Using sodium and iris.

**Comment by SoulxluoS** [comment]
Good afternoon, here are the settings in CEM mod?
![2022-09-26_16 02 30](https://user-images.githubusercontent.com/70120313/192938554-c5e80305-0c2f-4a6b-bfaf-00fed1cc76fe.png)

**Comment by SoulxluoS** [comment]
Tested now, everything works. If the advice from above does not help, then I suggest removing all texturpacks and mods and further adding them to check what is interfering.
