### ISSUE TITLE
I actually like the effect of sleeping with my eyes closed, but why close my eyes at work during the day

### ISSUE THREAD

**Issue by Saikel-Orado-Liu** [YoungSoulluoS/Fresh-Animations-CEM-fork#13]
FA version S5
CEM version S4
![2022-09-30_23 05 21](https://user-images.githubusercontent.com/88531138/193300227-f78c6863-91f3-46f5-b780-0d72a1bb5a6d.png)

**Comment by Saikel-Orado-Liu** [comment]
And Strange bug with spiders and cave spiders when loading the AddOn resource pack
![2022-09-30_23 22 43](https://user-images.githubusercontent.com/88531138/193303492-e4edcefc-7e9b-40aa-8088-3db232135414.png)
The skeleton's quiver did not appear too

**Comment by SoulxluoS** [comment]
> And Strange bug with spiders and cave spiders when loading the AddOn resource pack ![2022-09-30_23 22 43](https://user-images.githubusercontent.com/88531138/193303492-e4edcefc-7e9b-40aa-8088-3db232135414.png) The skeleton's quiver did not appear too

addon is built on JPM models, CEM does not support them

**Comment by SoulxluoS** [comment]
> FA version S5 CEM version S4 ![2022-09-30_23 05 21](https://user-images.githubusercontent.com/88531138/193300227-f78c6863-91f3-46f5-b780-0d72a1bb5a6d.png)

You need Update to CEM_S5 https://github.com/YoungSoulluoS/cemFork/releases
