### ISSUE TITLE
"enderman_eyes" not being emissive on enderman left arm and left leg

### ISSUE THREAD

**Issue by woodgoldtwo** [YoungSoulluoS/Fresh-Animations-CEM-fork#19]
Using: https://www.curseforge.com/minecraft/texture-packs/enderman-revamp

The pack above uses the "enderman_eyes" texture to add emissives to the enderman while being vanilla compatible. But it doesn't glow on the left arm and the left leg (the texture is still there it just doesn't glow)
![2022-10-15_15 19 45](https://user-images.githubusercontent.com/105434886/195989139-d29ecde5-c1ce-4bcd-a105-59b50bb20cb3.png)

**Comment by SoulxluoS** [comment]
To be fixed in FA v1.7_S7.
But the problem persists in general in CEM.
