### ISSUE TITLE
Villager eyebrows?

### ISSUE THREAD

**Issue by M1ChaeL756** [YoungSoulluoS/Fresh-Animations-CEM-fork#20]
i have a very weird glitch, everything seems to be working except the villagers eybrows, heres a screenie!
![2022-10-16_11 55 50](https://user-images.githubusercontent.com/109029222/196029198-731e909f-e324-45a5-8c42-b6924b023944.png)

**Comment by M1ChaeL756** [comment]
Theres also an interesting glitch with a horse
![2022-10-16_12 02 51](https://user-images.githubusercontent.com/109029222/196029447-49ce7cd3-3060-4664-93d6-02cd10431fa3.png)

**Comment by woodgoldtwo** [comment]
https://github.com/YoungSoulluoS/Fresh-Animations-CEM-fork/issues/17

**Comment by M1ChaeL756** [comment]
the horse is fixed, but the villager isn't and the pig looks like this
![2022-10-16_14 05 04](https://user-images.githubusercontent.com/109029222/196034496-ff5a021b-8725-4d86-a3ce-0e3828ff60d8.png)

**Comment by SoulxluoS** [comment]
Install CEM Fork https://github.com/YoungSoulluoS/cemFork/releases
