### ISSUE TITLE
Not full compatible with Xaeros-minimap

### ISSUE THREAD

**Issue by SebSemos** [YoungSoulluoS/Fresh-Animations-CEM-fork#22]
Icons on this minimap mod don't show for all of the mob from FA;

###  Mobs beiing ok:
>dolphin, drowned, elder guardian, ghast, guardian, husk, llama, magma cube, piglin, piglin brute, silverfish (but position not accurate by about 2 blocks), skeleton, stray, trader llama, wither skeleton, zombie, zombie villager, zombified piglin

### Mobs not showing icon: 
> blaze, cat, cave spider, chicken, cow, creeper, donkey, enderman, evoker, fox, hoglin, horse, illusioner, iron golem, mushroom, mule, ocelot, parrot, phantom, pig, pillager, ravager, sheep, skeleton horse, spider, strider, turtle, vex, villager, vindicator, wandering trader, witch, wolf/dog, zoglin, zombie horse,

It would be fantastic if we can have all of them on the radar :)

**Comment by SoulxluoS** [comment]
Hi.
This is because the head model is not in the vanilla root. It would require a major rewrite of the animation code to fix this. I'm not ready to do that right now. I suggest creating an issue on the original FA github. Maybe he will fix it in the next update. And I'll already move it here.

**Comment by SebSemos** [comment]
Ok, I understand, I'll check on the original then :)
