### ISSUE TITLE
Horse model not rendered correctly

### ISSUE THREAD

**Issue by barcedev** [YoungSoulluoS/Fresh-Animations-CEM-fork#23]
It seems like the offset of the horse's head is way lower than it's supposed to be. Affects horses, donkeys, and mules.
![2022-10-17_17 45 18](https://user-images.githubusercontent.com/20468242/196309671-79ab9622-c2e7-46b5-a4d9-43b3e9e53792.png)

**Comment by SoulxluoS** [comment]
Hi!
https://github.com/YoungSoulluoS/Fresh-Animations-CEM-fork/issues/17
