### ISSUE TITLE
动物还是会倒过来

### ISSUE THREAD

**Issue by 54dsa** [YoungSoulluoS/Fresh-Animations-CEM-fork#24]
绵羊会倒过来，蜘蛛没有腿和眼睛

**Comment by 54dsa** [comment]
![微信图片_20221025145614](https://user-images.githubusercontent.com/116626829/197707942-5d44f652-d570-4781-8a56-d2d2e2086acf.jpg)
绵羊会倒过来，蜘蛛没有腿和眼睛

**Comment by 54dsa** [comment]
![微信图片_20221025151946](https://user-images.githubusercontent.com/116626829/197709263-a1d1aa02-0fe7-4502-a900-44df1d72ae7d.jpg)
抱歉蜘蛛已经修复了但是羊有问题骷髅也有问题

**Comment by SoulxluoS** [comment]
Hi, try this
https://github.com/YoungSoulluoS/Fresh-Animations-CEM-fork/issues/17

**Comment by 54dsa** [comment]
> 嗨，试试这个#17还是一样的

**Comment by SoulxluoS** [comment]
And my translator didn't quite understand the answer. It helped, didn't it?
And if you can, please answer in English.

**Comment by 54dsa** [comment]
> 我的翻译不太明白答案。它有帮助，不是吗？如果可以的话，请用英语回答。

no
it doesn't work

**Comment by SoulxluoS** [comment]
Send here a screenshot of the folder with mods and texturpacks.

**Comment by 54dsa** [comment]
> 在此处发送包含模组和纹理包的文件夹的屏幕截图。

![微信图片_20221026134208](https://user-images.githubusercontent.com/116626829/197944250-eb02bdc7-e29e-4675-ba94-829e54e08638.jpg)
![微信图片_20221026134217](https://user-images.githubusercontent.com/116626829/197944309-ed711bb0-7b7a-42ec-9bd2-d2bdce5fe16f.jpg)
![微信图片_20221026134221](https://user-images.githubusercontent.com/116626829/197944317-09902fad-3a01-4de7-a928-e7b657fdc987.jpg)

**Comment by YoungSoulluoS** [comment]
Surely these are all mods?
I've looked through everything and can't find anything that might conflict. But there is a conflict. Some mod is changing the skeleton texture. The only option would be to manually go through the mods that add content. You'll have to do that.

**Comment by SoulxluoS** [comment]
Only install FA OR FA Addons. They work independently of each other and cause conflicts together.

**Comment by 54dsa** [comment]
> 仅安装 FA 或 FA 插件。它们彼此独立工作，共同造成冲突。

i try

**Comment by 54dsa** [comment]
I uninstalled the FA plugin  ，It's good now
