### ISSUE TITLE
Only the skeleton looks strange.

### ISSUE THREAD

**Issue by ipiiia** [YoungSoulluoS/Fresh-Animations-CEM-fork#25]
https://imgur.com/a/5rCSK70

All the other mobs seem to be working well.

**Comment by YoungSoulluoS** [comment]
Hi
Are you using texturepacks other than FA at the same time, or mods that modify Mob models?

**Comment by ipiiia** [comment]
> Hi
> Are you using texturepacks other than FA at the same time, or mods that modify Mob models?

Oh, I moved the add-on resource pack to the top, so it works well!

Thank you for making a great fork.

**Comment by YoungSoulluoS** [comment]
😉
