### ISSUE TITLE
Skeleton skull and baby skeletons look broken

### ISSUE THREAD

**Issue by gabriel-andreescu** [YoungSoulluoS/Fresh-Animations-CEM-fork#26]
Hi! Thanks for your amazing work!

I'm having the following issue with [tiny skeletons](https://www.curseforge.com/minecraft/mc-mods/tiny-skeletons-forge) mod, the vanilla skeleton head and also the baby skeleton from [more babies](https://www.curseforge.com/minecraft/mc-mods/more-babies)
![2022-10-27_01 33 16](https://user-images.githubusercontent.com/3175443/198151390-e32a7abf-32e1-4d7d-8ff0-325e18be704f.png)
![2022-10-27_01 33 26](https://user-images.githubusercontent.com/3175443/198151397-78b46275-d543-438c-9a79-33e2cc7665aa.png)

Everything else seems to work perfectly.
Thank you.

**Comment by marklangerhacker** [comment]
Baby skeleton?

**Comment by gabriel-andreescu** [comment]
[tiny skeletons](https://www.curseforge.com/minecraft/mc-mods/tiny-skeletons-forge)
[more babies](https://www.curseforge.com/minecraft/mc-mods/more-babies)

that's why I've linked the mods

**Comment by 54dsa** [comment]
You need to uninstall a FreshAnimations_v1.7_Add_S7 plugin, two plugins cannot be installed at the same time will conflict

**Comment by gabriel-andreescu** [comment]
@54dsa sorry but I do not understand, I only have one resource pack:
![image](https://user-images.githubusercontent.com/3175443/198242265-1a4c758f-f925-4173-bcc6-c2f778cece71.png)

**Comment by gabriel-andreescu** [comment]
replacing FreshAnimations_v1.7_Add_S7 with FreshAnimations_v1.7_S7 fixed the issue, so I guess there is a problem with the addon?

**Comment by SoulxluoS** [comment]
Hi, fixed, update in the next update. Thank you.
