### ISSUE TITLE
Problem with Vindicators

### ISSUE THREAD

**Issue by Owehttamy** [YoungSoulluoS/Fresh-Animations-CEM-fork#28]
If you surround a vindicator with 3x3 fences so they cannot move but can still see you, they'll raise their arm but not wield their axe, leading to a pose that some may deem offensive.
This behavior doesn't occur on the Optifine version of the game, and I have ensured that I have the proper settings displayed in #17.
<details>
  <summary>Example image:</summary>
  
  ![image](https://user-images.githubusercontent.com/47429979/198179904-eacd1851-10f3-4912-b519-dd9367f900f6.png)
  
</details>

**Comment by SebSemos** [comment]
I have to check, but I think this things happends to all "axe mobs" when you summon them without an AI too.

**Comment by SoulxluoS** [comment]
Hi, fixed, update in the next update. Thank you.

**Comment by SoulxluoS** [comment]
This problem helped me look differently at the logic of the CEM mod. There are ideas on how to fix some more problems in FA.

**Comment by Owehttamy** [comment]
> Hi, fixed, update in the next update. Thank you.

Do you mean the next update as in the next patch you make or v1.8 of the actual Fresh Animations resource pack?

**Comment by YoungSoulluoS** [comment]
For fork

**Comment by SoulxluoS** [comment]
> > Hi, fixed, update in the next update. Thank you.
> 
> Do you mean the next update as in the next patch you make or v1.8 of the actual Fresh Animations resource pack?

For fork
