### ISSUE TITLE
Sheep and horses broke

### ISSUE THREAD

**Issue by jazzathedev** [YoungSoulluoS/Fresh-Animations-CEM-fork#29]
![2022-10-30_11 14 40](https://user-images.githubusercontent.com/81956724/199631693-8322a790-6bfe-42c5-8922-bafbb7c41cd1.png)
![2022-10-30_11 20 49](https://user-images.githubusercontent.com/81956724/199631701-59406e35-43bd-4d33-bfc1-3248ef921db6.png)

Hi, I'm kinda new to github but I think this is the place to make a "bug report". I've noticed using this fresh animations fork the sheep and horses/skeleton horses are kinda broken, the sheep's bodies and heads show in the wrong place, and the horse's heads also show in the wrong place. I've got a lot of mods (about 95) but here's a list of the mods I think could contribute to this (I'm using fabric on 1.19):
entity_texture_features_fabric_1.19.x-4.1.1
cem-0.7.1_S7_1.19
horse-stats-vanilla-4.2.2
sheepconsistency-1.0.4
entity-texture-features-3.1.4-mc1.19 (not sure why this is here? Double ups seem to be ignored)
animatica-0.5+1.19
entityculling-fabric-1.5.2-mc1.19
cem-0.7.1

(If you want the full list here it is: https://www.mediafire.com/file/67q46xr446156xj/Jazzas_Mods_31.10.22.zip/file)
(If I've done anything wrong in this issue or you need more info, please tell me :D)

**Comment by SoulxluoS** [comment]
Hi! Read it
https://github.com/YoungSoulluoS/Fresh-Animations-CEM-fork/issues/17
