### ISSUE TITLE
Models really weird for sheep and horses

### ISSUE THREAD

**Issue by ZephyrysBaum** [YoungSoulluoS/Fresh-Animations-CEM-fork#30]
Folowed all the steps!
![image](https://user-images.githubusercontent.com/82797019/199919180-8003fc3f-db70-4c00-8f29-0652dbd9e1d8.png)
Mods:
![image](https://user-images.githubusercontent.com/82797019/199919398-a8d3b87f-0db3-43a8-8262-f85b0264de13.png)
![image](https://user-images.githubusercontent.com/82797019/199919461-0cb52140-248a-43e2-8c12-ca29a48dcfa0.png)
![image](https://user-images.githubusercontent.com/82797019/199919546-be364abb-f49f-46ed-af93-ed2ed93c9a48.png)
Resource packs:
![image](https://user-images.githubusercontent.com/82797019/199919741-58c5066a-7841-4065-af92-833bec35a51c.png)
Shaders:
![image](https://user-images.githubusercontent.com/82797019/199919798-a3bbfbb9-0a00-40a9-a6c9-7d8239472d3a.png)

**Comment by SoulxluoS** [comment]
https://github.com/YoungSoulluoS/Fresh-Animations-CEM-fork/issues/17

**Comment by ZephyrysBaum** [comment]
I SAID I TRIED ALL THE STEPS!

**Comment by Thanos1716** [comment]
are you absolutely sure you have [this](https://github.com/YoungSoulluoS/cemFork/releases) version of CEM installed?
