### ISSUE TITLE
Pig Variants Don't Blink and Main Pig Variant Has No Eyes

### ISSUE THREAD

**Issue by ayayrom** [YoungSoulluoS/Fresh-Animations-CEM-fork#32]
title^

this is a gif, not a image
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/61670781/200759462-3ef72152-96f6-466d-9859-d160ced5c9af.gif)

edit: forgot to mention that this also happens for the babies and this is from the Addon version
edit 2: this is also apparent in the cows as well, sheep just dont blink ever
edit 3: this also happens with wandering traders
edit 4: i just realized one of the mods provide varieties, this is a big bruh moment.
all of this is invalid, however, the "no eyes" is still an issue

**Comment by SoulxluoS** [comment]
You use a texture pack with random textures on top of the FA Addon. Naturally, this is not provided for in it. 
You can adapt it yourself and draw textures and blink animations by taking the pig texture from FA Addon as a sample.
Good luck

**Comment by R3ner** [comment]
> edit: forgot to mention that this also happens for the babies and this is from the Addon version edit 2: this is also apparent in the cows as well, sheep just dont blink ever edit 3: this also happens with wandering traders edit 4: i just realized one of the mods provide varieties, this is a big bruh moment. all of this is invalid, however, the "no eyes" is still an issue

Excuse me, what is the mod that provide variations? i trying to fix this too

**Comment by SoulxluoS** [comment]
ETF
> 
> 
> > edit: forgot to mention that this also happens for the babies and this is from the Addon version edit 2: this is also apparent in the cows as well, sheep just dont blink ever edit 3: this also happens with wandering traders edit 4: i just realized one of the mods provide varieties, this is a big bruh moment. all of this is invalid, however, the "no eyes" is still an issue
> 
> 
> 
> Excuse me, what is the mod that provide variations? i trying to fix this too
> 
>

**Comment by R3ner** [comment]
> 

Hi, thanks for the reply, I removed the mod variant but still have the glitch of blank eyes on pigs and some mobs, the rest works fine, but having herobrine mobs breaks the experience, any solutions? I already have your cem-0.7.1_S8_1.19-1.19.2.jar for my fabric 1.19.2, and fork 1.7 FA cem, also Entity Texture Features - [Fabric & Forge] (remove or not, problem persists) and Animatics. I tested in a separate profile without other texture packs, i also followed your guide for model and texture problems

**Comment by SoulxluoS** [comment]
And recommend use new EMF mod that replace CEM. It's better. And full support original FA 1.8
