### ISSUE TITLE
Phantom animations and model are disjointed from hitbox

### ISSUE THREAD

**Issue by Darmandir** [YoungSoulluoS/Fresh-Animations-CEM-fork#33]
Hello, I've been using your fork of CEM and Fresh animations and I absolutely love them, outstanding job!  I've found an issue with the phantom animations and model placement, however; the models are far above the hitbox for the phantom, and the animations aren't smooth for the phantom as they would be in the main Fresh Animations pack for Optifine, the phantoms sort of jerk around. I have attached some screenshots to illustrate the model placement issue.

Vanilla:
![2022-11-09_18 29 28](https://user-images.githubusercontent.com/45914359/200971266-7b37a458-b5c4-4cc9-ad0b-de84ae436d7e.png)

FA CEM Fork S8:
![2022-11-09_18 26 47](https://user-images.githubusercontent.com/45914359/200971337-167544a4-afe3-4bf0-8d71-f73ebab854cb.png)
![2022-11-09_18 26 49](https://user-images.githubusercontent.com/45914359/200971348-e324b911-7a5b-42ca-bddf-595f7754ab93.png)

Another thing is that FA v1.7 S8 Add retains the wing particles (in the wrong place, they are where they would be for a vanilla phantom) and the regular S8 pack does not have the particles.

Again, this project is awesome, but this issue really makes phantoms quite a challenge to fight! :P

**Comment by SoulxluoS** [comment]
Fixed model placement, redownload _S8.
Particles placement are probably not supported by CEM.
