### ISSUE TITLE
Don't break the cat!

### ISSUE THREAD

**Issue by ToxicXremade** [YoungSoulluoS/Fresh-Animations-CEM-fork#35]
https://media.essential.gg/7ab42f87-b1cf-458f-ebed-76cba5365700

no other texture packs, using all required dependencies.

**Comment by SoulxluoS** [comment]
https://github.com/YoungSoulluoS/Fresh-Animations-CEM-fork/issues/17

**Comment by idkh3lpme** [comment]
![image](https://user-images.githubusercontent.com/118058718/201809253-18660d4c-e55a-4822-bafc-643b323586b6.png)
