### ISSUE TITLE
Support for FA addons

### ISSUE THREAD

**Issue by MincedRaft** [YoungSoulluoS/Fresh-Animations-CEM-fork#36]
Is there any plan to convert any of the third-party FA addon packs, such as https://www.planetminecraft.com/texture-pack/fresh-alex-zombies-fresh-animations/ to be compatible with this Fork?

**Comment by Thanos1716** [comment]
if you like i can give you a tweaked version of FA that includes that addon (or others if you like, it'll take me like 5 minutes for that one), but the ultimate goal is to get them working without conversion, so i wouldn't count on it

**Comment by SoulxluoS** [comment]
Not planning to

**Comment by Thanos1716** [comment]
@MincedRaft was bored so here you go (standalone, since this mod doesn't support .jpm files yet)
[FreshAnimations_v1.7_S8_Alex_Zombies.zip](https://github.com/YoungSoulluoS/Fresh-Animations-CEM-fork/files/10015087/FreshAnimations_v1.7_S8_Alex_Zombies.zip)
[FreshAnimations_v1.7_Add_S8_Alex_Zombies.zip](https://github.com/YoungSoulluoS/Fresh-Animations-CEM-fork/files/10015086/FreshAnimations_v1.7_Add_S8_Alex_Zombies.zip)

**Comment by MincedRaft** [comment]
> @MincedRaft was bored so here you go (standalone, since this mod doesn't support .jpm files yet) [FreshAnimations_v1.7_S8_Alex_Zombies.zip](https://github.com/YoungSoulluoS/Fresh-Animations-CEM-fork/files/10015087/FreshAnimations_v1.7_S8_Alex_Zombies.zip) [FreshAnimations_v1.7_Add_S8_Alex_Zombies.zip](https://github.com/YoungSoulluoS/Fresh-Animations-CEM-fork/files/10015086/FreshAnimations_v1.7_Add_S8_Alex_Zombies.zip)

Thank you!

**Comment by SebSemos** [comment]
Hey guys, hope you don't mind me to ask this there but: I am currently making the villager to have a player model to apply skin textures. 
I was just wondering what was the "rotation" subgroup in "body/head2" ? Can''t figure out what it's there for ^^ 

And in the same time @YoungSoulluoS Do you mind if I share the ressource pack(s) I have in minde with this modified model? (with due credit to you and FA obviously) :)

**Comment by SoulxluoS** [comment]
@SebSemos 
Can't remember what the "rotation" is.
Open model in Blockbench and you can see.
Use the model, no problem.

**Comment by SebSemos** [comment]
It was simply the display for the hat of the profession ^^
Thx for the approuval :)
