### ISSUE TITLE
If I disable new model creation fix pig breaks, if I enable it pig is fixed but sheep and horse breaks

### ISSUE THREAD

**Issue by ToxicXremade** [YoungSoulluoS/Fresh-Animations-CEM-fork#37]
Using the latest version of cem soulfork and all other dependencies, only other texture packs are bare bones and a compatibility pack, but have been tested without them and have the same results as with them. Screenshots:
With new model creation fix:
![2022-11-16_19 53 43](https://user-images.githubusercontent.com/118058718/202334868-44eb7ade-1f45-43bf-9d37-c1b975a023c6.png)
Without new model creation fix:
![2022-11-16_19 56 44](https://user-images.githubusercontent.com/118058718/202338394-d21c690e-9159-46db-9a91-88f9ab48e0eb.png)
help?

**Comment by SoulxluoS** [comment]
You need to use "model creation fix = OFF". About the pig. Apparently the Bare Bones package isn't compatible. There's no problem on my end. You can adapt the pig model yourself using Blockbench. Maybe you need to flip the "Body" part to 90 or -90. Good luck

**Comment by ToxicXremade** [comment]
> You need to use "model creation fix = OFF". About the pig. Apparently the Bare Bones package isn't compatible. There's no problem on my end. You can adapt the pig model yourself using Blockbench. Maybe you need to flip the "Body" part to 90 or -90. Good luck

I already said I have a compatibility pack for it, and I have tested freshanimations without any other packs and it is still happening. Also I tried the blockbench method and its broken the models even more

**Comment by Thanos1716** [comment]
I had this issue while using the original CEM (not soul fork) so I would double check you are using the latest releases of both the cem soul fork and fresh animations cem fork, if you have the original cem in your mods folder, I just tested it and it loads before the soul fork and then causes the soul fork not to load, so check that you are using the right cem and that its the only cem in the mods folder

**Comment by ToxicXremade** [comment]
> I had this issue while using the original CEM (not soul fork) so I would double check you are using the latest releases of both the cem soul fork and fresh animations cem fork, if you have the original cem in your mods folder, I just tested it and it loads before the soul fork and then causes the soul fork not to load, so check that you are using the right cem and that its the only cem in the mods folder

Yes, I am using the latest version of the pack and CEM soulfork

**Comment by Thanos1716** [comment]
Try reinstalling everything on a new instance
