### ISSUE TITLE
how do i fix this

### ISSUE THREAD

**Issue by Saibot2OO6** [YoungSoulluoS/Fresh-Animations-CEM-fork#40]
hey there are a few model problems i have noticed and I'm here to make you aware to them, first all horse variants, sheep, donkey have their heads in the ground, I'm not to sure how to fix this issue, both guardians have their parts in weird places like all their spikes out the top of their heads, etc, and the hoglin but not the zoglin has their head on funny, i see you discord has already addressed the hoglin issue, the trader's lama also has a weird animation error you could look into if you have the time, that is all for now,

keep up the good work,
Sai

**Comment by Thanos1716** [comment]
sounds like you have a configuration issue, try checking everything in #17

**Comment by Saibot2OO6** [comment]
I have already reviewed solution 17, thanks for your concern, I shall review it again for a closer examination, thank you for your time

Sent on the go with Vodafone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SoulxluoS** [comment]
🙂
