### ISSUE TITLE
[Bug] Enderman Left Leg is on the Right in the model

### ISSUE THREAD

**Issue by Thanos1716** [YoungSoulluoS/Fresh-Animations-CEM-fork#41]
A minor bug, but I figured i would point it out anyway.
In the Enderman model, if you view the model without animations, the Enderman left leg is on the right side of the body, and vice versa for the right on the left, but once animations are running, this is corrected.

**Comment by SoulxluoS** [comment]
Hi,
I don't understand. I need is a photo or a video.

**Comment by Thanos1716** [comment]
Alright, here you go
Notice the colours of the legs switch:
Without animations (left) and with custom animations playing (right):
![Screenshot_20221214_213339](https://user-images.githubusercontent.com/80975570/207719731-50b80c9f-ed9b-4a8d-9611-2702cd1c3d7f.png)![Screenshot_20221214_213402](https://user-images.githubusercontent.com/80975570/207719800-96ec08f9-a5c5-4fef-9bd4-6a59c123d566.png)

**Comment by Thanos1716** [comment]
this is actually an upstream issue with the original Fresh Animations anyway, so nevermind

**Comment by SoulxluoS** [comment]
Well I haven't noticed any problems in the fork, so we're closing.
