### ISSUE TITLE
[Suggestion] More specific release info

### ISSUE THREAD

**Issue by Eiion** [YoungSoulluoS/Fresh-Animations-CEM-fork#42]
Currently being in the process of giving your modifications of Fresh Animations a try I find myself confused about differences between [FreshAnimations_v1.7_Add_S9.zip](https://github.com/YoungSoulluoS/Fresh-Animations-CEM-fork/releases/download/v1.7_S9/FreshAnimations_v1.7_Add_S9.zip) and [FreshAnimations_v1.7_S9.zip](https://github.com/YoungSoulluoS/Fresh-Animations-CEM-fork/releases/download/v1.7_S9/FreshAnimations_v1.7_S9.zip)
If the release info contained a bit more info regarding what's what (i.e. what's the difference between the two) that would really be helpful. 

Offtopic: Many thanks for your work for us to appreciate some fresh animations in the game!

**Comment by SoulxluoS** [comment]
😉

**Comment by ItsIgnacioPortal** [comment]
> 😉

So, could you tell us the difference?

**Comment by SoulxluoS** [comment]
Everything here except the slime
https://www.curseforge.com/minecraft/texture-packs/fresh-animations-extensions
