### ISSUE TITLE
WilderWilds mod pig body axis bug

### ISSUE THREAD

**Issue by VinnyStalck** [YoungSoulluoS/Fresh-Animations-CEM-fork#43]
When using [WildWilds mod](https://github.com/FrozenBlock/WilderWild), pigs have an altered x rotation axis for some reason

Minecraft: 1.19.2

Wilder Wild: 1.1.5
CEM Fork: 0.7.1_S8_1.19-1.19.2

Fresh Animations Fork:  1.7_S8 + 1.7_Add_S8

[Minecraft Log using Quilt](https://mclo.gs/cAfO5Ml)
[Minecraft Log using Fabric](https://mclo.gs/6ZacF4E)

![image](https://user-images.githubusercontent.com/42945819/208927034-110730bb-2032-4dfb-9b9f-5509ece41891.png)
none of the other resource packs had an impact on this btw

**Comment by SoulxluoS** [comment]
Obviously the problem is in mod, you'll have to sort that out.
