### ISSUE TITLE
Eyeless bug with Pickable Villagers Mod

### ISSUE THREAD

**Issue by Hero-Wether** [YoungSoulluoS/Fresh-Animations-CEM-fork#46]
![HV](https://user-images.githubusercontent.com/57046947/211400234-5f7806e3-3234-4d5f-9514-4bade8fb7582.PNG)

<h3>This bug is present when used with using Fresh Animations with <a href="https://www.curseforge.com/minecraft/mc-mods/pickable-villagers">Pickable Villagers</a></h3>

**Comment by SoulxluoS** [comment]
Use this fork for you.

[FreshAnimations_v1.7_S9_Pickable_Villagers.zip](https://github.com/YoungSoulluoS/Fresh-Animations-CEM-fork/files/10404393/FreshAnimations_v1.7_S9_Pickable_Villagers.zip)
[FreshAnimations_v1.7_Add_S9_Pickable_Villagers.zip](https://github.com/YoungSoulluoS/Fresh-Animations-CEM-fork/files/10404394/FreshAnimations_v1.7_Add_S9_Pickable_Villagers.zip)
