### ISSUE TITLE
The villagers have no eyes

### ISSUE THREAD

**Issue by Crushedfish4740** [YoungSoulluoS/Fresh-Animations-CEM-fork#48]
The villagers have no eyes
![2023-01-12_20 41 41](https://user-images.githubusercontent.com/116926683/212069457-4193c13d-0115-4c5c-87e1-136713203a36.png)

**Comment by SoulxluoS** [comment]
https://github.com/YoungSoulluoS/Fresh-Animations-CEM-fork/issues/17
