### ISSUE TITLE
is_sleeping

### ISSUE THREAD

**Issue by SebSemos** [YoungSoulluoS/Fresh-Animations-CEM-fork#49]
I hate to open an issue for that, because it is not really one, but I don't know what better way to contact you ^^

So I have been messing with the villager model for some time, I have added facial animations in my ressource pack with the sleep feature. But I don't like how the eyes keep poping from the texture areas still. Especially with emissive eyes ^^

So I get a look to the sleep part and the is_sleeping variant. But I can't reverse ingeniere it properly. Anything I tried to integrate into the eyes failed. At best, I had the eyes hidden while sleeping (good), but they were hidden/shown randomly while not sleeping (half good ^^)

Could you elaborate some info on this one as it is not part of the optifine format, I've found anything on this.

**Comment by SoulxluoS** [comment]
Hi. The is_sleeping condition checks if the villager is asleep and then performs the animation or not. Drop your resourcespack here or to me on discord. I'll see what I can do or fix it.

**Comment by SebSemos** [comment]
Thx. I'm on the right track then. But I just realise i think i did my testing only on one axis. Wich might be why I get the random stuff. 
I'm gonna test more when I got some Time and if no results I'll send you the pack 🙂
But where do I find your discord ?

**Comment by SoulxluoS** [comment]
Soul_luoS#3889
