### ISSUE TITLE
Update to Version 1.8

### ISSUE THREAD

**Issue by Owehttamy** [YoungSoulluoS/Fresh-Animations-CEM-fork#50]
FreshLX has graced us with the [1.8 update](https://www.curseforge.com/minecraft/texture-packs/fresh-animations/files/4360370) today!

Of course, I don't expect you to update both the CEM fork and provide compatibility with Fresh Animations by tomorrow or something crazy, but this is to notify you that the update has been released if you weren't previously aware.

I am excited to experience it on Fabric when you have the time to rewrite it for compatibility. Thanks!

**Comment by SoulxluoS** [comment]
Hi, I'm not going to update. The new FA version contains many things that the current version of CEM does not work. And most importantly, another promising CEM mod by Traben is in development right now.https://discord.gg/se48NgYn
