### ISSUE TITLE
Invisible mobs with fresh animations

### ISSUE THREAD

**Issue by ItsVex** [YoungSoulluoS/Fresh-Animations-CEM-fork#52]
When i turn the option 'config.use_optifine_folder' on and reload my resource pack the mobs turn invisible.

Here is the resource pack im using
[FreshAnimations_v1.7_S9.zip](https://github.com/YoungSoulluoS/Fresh-Animations-CEM-fork/files/10679838/FreshAnimations_v1.7_S9.zip)

**Comment by SoulxluoS** [comment]
Hi,
Read https://github.com/YoungSoulluoS/Fresh-Animations-CEM-fork/issues/17

**Comment by ItsVex** [comment]
I have done everything in that post, still doesn't work.

**Comment by SoulxluoS** [comment]
Screenshot your mod and resource pack

**Comment by Xzeryn** [comment]
I had this problem earlier today when I upgraded sodium to 0.4.9 and iris to 1.5.2, reverting back to 0.4.8 and 1.5.1 fixed it for me.  The Iris change log mentioned things could break with upgrading sodium.

**Comment by ItsVex** [comment]
![texture packs](https://user-images.githubusercontent.com/115067053/217420651-948f24d1-6abd-40e1-bc02-462b854e4eaf.PNG)

![my mods](https://user-images.githubusercontent.com/115067053/217420653-5d1006e3-f89b-4853-9826-68468dbd03ae.PNG)

**Comment by SoulxluoS** [comment]
> ![texture packs](https://user-images.githubusercontent.com/115067053/217420651-948f24d1-6abd-40e1-bc02-462b854e4eaf.PNG)
> 
> 
> 
> ![my mods](https://user-images.githubusercontent.com/115067053/217420653-5d1006e3-f89b-4853-9826-68468dbd03ae.PNG)
> 
> 

First, you use no CEM Fork, read FAQ and install S9.

**Comment by ItsVex** [comment]
my bad, I don't have it enabled right now but I was using it earlier when I made the ticket.

![Capture](https://user-images.githubusercontent.com/115067053/217422404-75a8f5a1-7657-47c9-83ce-361a8935559d.PNG)

**Comment by SoulxluoS** [comment]
You need install this mod https://github.com/YoungSoulluoS/cemFork/releases/tag/Soul_Fork_9 Instead of cem 0.7.1

**Comment by Xzeryn** [comment]
@YoungSoulluoS even with the latest fork installed mobs that are affected by fresh animations are throwing error messages in the console when I upgraded to sodium 0.4.9.  Downgrading back to 0.4.8 fixed it.

Here are some of the messages I'm getting in the console.

`<log4j:Event logger="Custom Entity Models" timestamp="1675824527578" level="WARN" thread="Render thread">
    <log4j:Message><![CDATA[	the above file didn't specify all uv directions!]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="Custom Entity Models" timestamp="1675824527578" level="WARN" thread="Render thread">
    <log4j:Message><![CDATA[	the above file didn't specify all uv directions!]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="Custom Entity Models" timestamp="1675824527578" level="WARN" thread="Render thread">
    <log4j:Message><![CDATA[	the above file didn't specify all uv directions!]]></log4j:Message>
  </log4j:Event>

actions.js:3272   <log4j:Event logger="Custom Entity Models" timestamp="1675824527578" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[minecraft:optifine/cem/creeper.jem]]></log4j:Message>
  </log4j:Event>

actions.js:3272   <log4j:Event logger="Custom Entity Models" timestamp="1675824527579" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[minecraft:optifine/cem/dolphin.jem]]></log4j:Message>
  </log4j:Event>

actions.js:3272   <log4j:Event logger="Custom Entity Models" timestamp="1675824527579" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[minecraft:optifine/cem/donkey.jem]]></log4j:Message>
  </log4j:Event>

2actions.js:3272   <log4j:Event logger="Custom Entity Models" timestamp="1675824527579" level="WARN" thread="Render thread">
    <log4j:Message><![CDATA[	the above file didn't specify all uv directions!]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="Custom Entity Models" timestamp="1675824527579" level="WARN" thread="Render thread">
    <log4j:Message><![CDATA[	the above file didn't specify all uv directions!]]></log4j:Message>
  </log4j:Event>

actions.js:3272   <log4j:Event logger="Custom Entity Models" timestamp="1675824527579" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[minecraft:optifine/cem/drowned.jem]]></log4j:Message>
  </log4j:Event>

actions.js:3272   <log4j:Event logger="Custom Entity Models" timestamp="1675824527580" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[minecraft:optifine/cem/elder_guardian.jem]]></log4j:Message>
  </log4j:Event>

actions.js:3272   <log4j:Event logger="Custom Entity Models" timestamp="1675824527580" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[minecraft:optifine/cem/enderman.jem]]></log4j:Message>
  </log4j:Event>

actions.js:3272   <log4j:Event logger="Custom Entity Models" timestamp="1675824527580" level="WARN" thread="Render thread">
    <log4j:Message><![CDATA[	the above file didn't specify all uv directions!]]></log4j:Message>
  </log4j:Event>

actions.js:3272   <log4j:Event logger="Custom Entity Models" timestamp="1675824527580" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[minecraft:optifine/cem/evoker.jem]]></log4j:Message>
  </log4j:Event>

actions.js:3272   <log4j:Event logger="Custom Entity Models" timestamp="1675824527580" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[minecraft:optifine/cem/fox.jem]]></log4j:Message>
  </log4j:Event>

actions.js:3272   <log4j:Event logger="Custom Entity Models" timestamp="1675824527581" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[minecraft:optifine/cem/ghast.jem]]></log4j:Message>
  </log4j:Event>

actions.js:3272   <log4j:Event logger="Custom Entity Models" timestamp="1675824527581" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[minecraft:optifine/cem/giant.jem]]></log4j:Message>
  </log4j:Event>

actions.js:3272   <log4j:Event logger="Custom Entity Models" timestamp="1675824527581" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[minecraft:optifine/cem/guardian.jem]]></log4j:Message>
  </log4j:Event>

actions.js:3272   <log4j:Event logger="Custom Entity Models" timestamp="1675824527581" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[minecraft:optifine/cem/hoglin.jem]]></log4j:Message>
  </log4j:Event>

actions.js:3272   <log4j:Event logger="Custom Entity Models" timestamp="1675824527581" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[minecraft:optifine/cem/horse.jem]]></log4j:Message>
  </log4j:Event>

2actions.js:3272   <log4j:Event logger="Custom Entity Models" timestamp="1675824527581" level="WARN" thread="Render thread">
    <log4j:Message><![CDATA[	the above file didn't specify all uv directions!]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="Custom Entity Models" timestamp="1675824527581" level="WARN" thread="Render thread">
    <log4j:Message><![CDATA[	the above file didn't specify all uv directions!]]></log4j:Message>
  </log4j:Event>

actions.js:3272   <log4j:Event logger="Custom Entity Models" timestamp="1675824527582" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[minecraft:optifine/cem/husk.jem]]></log4j:Message>
  </log4j:Event>

actions.js:3272   <log4j:Event logger="Custom Entity Models" timestamp="1675824527582" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[minecraft:optifine/cem/illusioner.jem]]></log4j:Message>
  </log4j:Event>

actions.js:3272   <log4j:Event logger="Custom Entity Models" timestamp="1675824527583" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[minecraft:optifine/cem/iron_golem.jem]]></log4j:Message>
  </log4j:Event>

actions.js:3272   <log4j:Event logger="Custom Entity Models" timestamp="1675824527583" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[minecraft:optifine/cem/llama.jem]]></log4j:Message>
  </log4j:Event>`

**Comment by SoulxluoS** [comment]
It's new Sodium entity perfomance no compatible with this CEM version.
Wait CEM update from [dorianpb](https://github.com/dorianpb/cem) or a CEM release from [Traben.](https://discord.com/invite/rURmwrzUcz)
