### ISSUE TITLE
Entities invisible

### ISSUE THREAD

**Issue by N-Ved** [YoungSoulluoS/Fresh-Animations-CEM-fork#53]
The entities aren't rendering with the latest version of sodium..
![image](https://user-images.githubusercontent.com/87060868/217601272-3da3d34b-f6f2-4aa9-8e58-955e44881cbe.png)

**Comment by SoulxluoS** [comment]
Wait CEM update from [dorianpb](https://github.com/dorianpb/cem) or a CEM release from [Traben.](https://discord.com/invite/rURmwrzUcz)
