### ISSUE TITLE
Mobs Invisible

### ISSUE THREAD

**Issue by DEVLlN** [YoungSoulluoS/Fresh-Animations-CEM-fork#54]
All mobs that are effected by the resource pack just go invisible. I've installed the forks, and all mods that I need to have. I've also made sure that CEM has the correct settings that you posted on here. I've tested it with the resource pack alone and it still didn't work so theres not a conflicting pack. I can't think of any mods that I have installed that wouldn't be compatible with CEM. Any ideas? 

![Screenshot 2023-02-14 231155](https://user-images.githubusercontent.com/54874724/218927798-2dbd2fe6-99a9-47dd-8ca5-a0041f53000e.png)

**Comment by SoulxluoS** [comment]
Hi, fork not support sodium 0.4.9 now, use sodium 0.4.8.

**Comment by SoulxluoS** [comment]
https://github.com/YoungSoulluoS/cemFork/releases
