### ISSUE TITLE
sheep have a skill issue

### ISSUE THREAD

**Issue by LordEnder-Kitty** [YoungSoulluoS/Fresh-Animations-CEM-fork#56]
i haven't seen to many of the mobs yet but i thought i should mention that the sheeps body and heads are upside down for some reason

**Comment by SoulxluoS** [comment]
> haven't seen to many of the mobs yet but i thought i should mention that the sheeps body and heads are upside down for some reason

Hi, 
- sheep screenshot
- mods screenshot
- texture pack screenshot 
- CEM config screenshot

**Comment by SoulxluoS** [comment]
> i haven't seen to many of the mobs yet but i thought i should mention that the sheeps body and heads are upside down for some reason

And read https://github.com/YoungSoulluoS/Fresh-Animations-CEM-fork/issues/17
