### ISSUE TITLE
buggy models + herobrine eyes

### ISSUE THREAD

**Issue by papamaionise** [YoungSoulluoS/Fresh-Animations-CEM-fork#57]
![2023-03-03_23 14 52](https://user-images.githubusercontent.com/126779287/222800781-8d41809a-d83f-4a0c-a837-3e5e54671e3e.png)
![2023-03-03_23 15 53](https://user-images.githubusercontent.com/126779287/222800931-c3ed688a-fef1-4685-ab84-475c328ce0c7.png)
![2023-03-03_23 16 19](https://user-images.githubusercontent.com/126779287/222801027-52c5cbd2-8f0b-4ebb-a3d6-8e709467e2e3.png)
![2023-03-03_23 17 44](https://user-images.githubusercontent.com/126779287/222801032-32253cb1-e44e-43cc-af01-48d923516138.png)
![2023-03-03_23 17 48](https://user-images.githubusercontent.com/126779287/222801061-2b799a9a-dc40-4dcf-b38b-7986cd5fad9c.png)
![2023-03-03_23 29 40](https://user-images.githubusercontent.com/126779287/222801121-dfce5158-2b5b-49a1-bae0-cb41f4790117.png)
![2023-03-03_23 29 50](https://user-images.githubusercontent.com/126779287/222801131-458dc9cb-50d3-4386-96e3-1976b8ccffa9.png)
![2023-03-03_23 30 09](https://user-images.githubusercontent.com/126779287/222801140-730fab3a-cb68-4a52-ad1c-c2ba754d5678.png)
![2023-03-03_23 30 14](https://user-images.githubusercontent.com/126779287/222801146-04466729-f763-445d-8c95-4a2dbf9365f3.png)
![2023-03-03_23 30 19](https://user-images.githubusercontent.com/126779287/222801155-eb756b00-7df8-481e-98a6-8f98b850fc1a.png)
![2023-03-03_23 32 00](https://user-images.githubusercontent.com/126779287/222801163-76698b07-039a-470c-8b9a-5a38907afa50.png)
![2023-03-03_23 32 10](https://user-images.githubusercontent.com/126779287/222801170-1bcd1fba-cefb-443f-9fe8-629ed325bcb6.png)
![2023-03-03_23 32 15](https://user-images.githubusercontent.com/126779287/222801182-dbc79b25-34a2-4c6b-ab2f-f9b54563b137.png)
![2023-03-03_23 32 19](https://user-images.githubusercontent.com/126779287/222801189-9f770406-fee0-4af5-87d1-a82d5ccf291e.png)
![2023-03-03_23 32 59](https://user-images.githubusercontent.com/126779287/222801193-a1e55330-1a4e-46c8-9161-b59909fe9001.png)
![2023-03-03_23 33 22](https://user-images.githubusercontent.com/126779287/222801200-1faa4c78-2aee-42d7-8a10-6eda63a3b385.png)
![2023-03-03_23 33 41](https://user-images.githubusercontent.com/126779287/222801208-e241c210-cfee-4511-909c-6982851ba125.png)
![2023-03-03_23 33 53](https://user-images.githubusercontent.com/126779287/222801216-1dcf82ad-b97d-4857-88c8-350cbb51c5b8.png)
![2023-03-03_23 33 59](https://user-images.githubusercontent.com/126779287/222801220-1fe3c629-9feb-4a50-85e7-899d6affac05.png)
![2023-03-03_23 34 33](https://user-images.githubusercontent.com/126779287/222801229-feedeb3b-7c41-4f04-ab18-3fdfc22d9779.png)
![2023-03-03_23 34 36](https://user-images.githubusercontent.com/126779287/222801230-b4eab4a6-71e6-4e9e-88ae-d57a5daf853b.png)
![2023-03-03_23 34 39](https://user-images.githubusercontent.com/126779287/222801237-05d92cb8-f128-416a-988d-377478ca9b4e.png)
![2023-03-03_23 34 56](https://user-images.githubusercontent.com/126779287/222801241-c6b04e78-375c-49f6-8ff3-7508b829c0bd.png)
![2023-03-03_23 35 14](https://user-images.githubusercontent.com/126779287/222801256-f1c96e05-62b9-4d9f-8134-2facb3b3cf7c.png)
im confused af see for youself and help me plz ;-;

**Comment by SoulxluoS** [comment]
Hi, read https://github.com/YoungSoulluoS/Fresh-Animations-CEM-fork/issues/17

**Comment by papamaionise** [comment]
@YoungSoulluoS  I AM REALLY SORRY FOR WASTING YOUR TIME  im so dumb i used original cem instead of fork i was following an old tutorial thanks a lot
