### ISSUE TITLE
Llama clothes bug

### ISSUE THREAD

**Issue by Nikifta** [YoungSoulluoS/Fresh-Animations-CEM-fork#58]
A bug with the llama's clothes, the llama herself has animation, but her clothes don't. Because of this, artifacts appear
![2023-03-08_17 26 41](https://user-images.githubusercontent.com/105110534/223689128-98c7ba3d-a362-4dba-a07b-b39f8cd269c8.png)
![2023-03-08_17 26 41_2](https://user-images.githubusercontent.com/105110534/223689169-7a38029e-eb5e-4b92-aa32-2ec8a71c29d0.png)
![2023-03-08_17 25 38](https://user-images.githubusercontent.com/105110534/223689210-247a248f-6ce5-46f8-9af4-d7b698b0d27e.png)
![image](https://user-images.githubusercontent.com/105110534/223689499-5f27519e-5833-4e07-adee-a8c9cf92478a.png)

**Comment by SoulxluoS** [comment]
Hi, Thank you. CEM not support this. There won't be a fix from me. Wait CEM update from [dorianpb](https://github.com/dorianpb/cem) or a EMF release from [Traben.](https://discord.com/invite/rURmwrzUcz)

**Comment by Nikifta** [comment]
Mmm, ok, thx
