### ISSUE TITLE
Armor model render problem

### ISSUE THREAD

**Issue by Woohard** [YoungSoulluoS/Fresh-Animations-CEM-fork#60]
![2023-03-19_19 25 45](https://user-images.githubusercontent.com/128312086/226189897-07d49199-8f44-4334-9a48-b2d37fbecd05.png)
Armor model on skeletons renders incorrectly (left arm and leg). Is this because I'm using 1.18 version of minecraft maybe?
![2023-03-19_19 39 21](https://user-images.githubusercontent.com/128312086/226191705-aa72419f-89d7-4f68-8717-ca10ed42212e.png)

**Comment by YoungSoulluoS** [comment]
Hi, texturepack?

**Comment by YoungSoulluoS** [comment]
> ![2023-03-19_19 25 45](https://user-images.githubusercontent.com/128312086/226189897-07d49199-8f44-4334-9a48-b2d37fbecd05.png) Armor model on skeletons renders incorrectly (left arm and leg). Is this because I'm using 1.18 version of minecraft maybe? ![2023-03-19_19 39 21](https://user-images.githubusercontent.com/128312086/226191705-aa72419f-89d7-4f68-8717-ca10ed42212e.png)
Hi, texturepack?

**Comment by SoulxluoS** [comment]
You can redownload new CEM 1.18 fork with fix https://github.com/YoungSoulluoS/cemFork/releases/tag/Soul_Fork_10_1.19.4
