### ISSUE TITLE
Request for Fresh animations addon packs support by creepermax123

### ISSUE THREAD

**Issue by papamaionise** [YoungSoulluoS/Fresh-Animations-CEM-fork#62]
I have tried they make mobs go invisible
they work fine with optifine and normal fresh animations
so plzzz these aren't some low quality resource packs 
and im sure other people want this too
https://www.curseforge.com/members/creepermax123/projects

**Comment by SoulxluoS** [comment]
Use new EMF mod

- https://modrinth.com/mod/entity-model-features
- Creator [Traben.](https://discord.com/invite/rURmwrzUcz)

**Comment by papamaionise** [comment]
> Use new EMF mod
> 
> * https://modrinth.com/mod/entity-model-features
> * Creator [Traben.](https://discord.com/invite/rURmwrzUcz)

they are still invisible with this mod and fresh animations are broken too yes I used the original pack not your modified FA
plzz look into it if you've got time and make them compatible too just like you made fresh animations extensions pack

**Comment by SoulxluoS** [comment]
You have done something wrong. Install only EMF and only Fresh Animations 1.8

**Comment by SoulxluoS** [comment]
Other mods from creeper max may incompatible because EMF in BETA. Wait update.
Now you can fix invisible model in Blockbench. Need delete duplicate model parts.

**Comment by papamaionise** [comment]
> Other mods from creeper max may incompatible because EMF in BETA. Wait update. Now you can fix invisible model in Blockbench. Need delete duplicate model parts.

Alright then I'll wait thanks for your time sir and I'm sure I did nothing wrong the fresh animations glitches were those which they mentioned on mod page like frogs legs and stuff so it was installed correctly

**Comment by papamaionise** [comment]
> Other mods from creeper max may incompatible because EMF in BETA. Wait update. Now you can fix invisible model in Blockbench. Need delete duplicate model parts.

when using those packs with your fork some models work correctly the default one's have white eyes
