### ISSUE TITLE
Sheeps wool is floating above the sheep

### ISSUE THREAD

**Issue by dwnsdp** [YoungSoulluoS/Fresh-Animations-CEM-fork#63]

**Comment by dwnsdp** [comment]
![image](https://github.com/YoungSoulluoS/Fresh-Animations_cem_Fork/assets/112968215/114416cc-e771-485f-aa2c-a151e01b42aa)

**Comment by offbeat-stuff** [comment]
Are you using the right mod resourcepack combo?

**Comment by dwnsdp** [comment]
I have EMF and ETF

**Comment by offbeat-stuff** [comment]
if you have emf why bother here go bug tr7zw he maintains the mods.
This is a cem fork.

**Comment by williamogle0** [comment]
> I have EMF and ETF

to the extent of my knowlege, EMF performs the same task as CEM, so probably having both is causing the error

**Comment by SoulxluoS** [comment]
Use only EMF and ETF. CEM is deprecate.
